# See the example config: https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml
MD013: # Line length
  line_length: 100
  tables: false
MD033: # no-inline-html
  allowed_elements: ["iframe", "sup", "kbd"]
