name: Linter

on: [pull_request]

jobs:
  markdown-linter:
    name: "Markdown Linter"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: .
          config_file: .markdownlint.yaml

  markdown-link-check:
    name: "Markdown Link Checker"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: gaurav-nelson/github-action-markdown-link-check@1.0.15
